# Generated by Django 4.2 on 2023-05-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auther_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
