# Generated by Django 4.2 on 2023-05-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_users_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_watchlist',
            old_name='list_id',
            new_name='listing_id',
        ),
    ]
