# Generated by Django 4.2 on 2023-05-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_list_id_users_watchlist_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bidder',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
