# Generated by Django 4.2 on 2023-05-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_comment_auther_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highest_bidder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
